nome = str(input('Digite seu nome completo:')).strip()
n = nome.split()
print('E um prazer te conhecer !')
print(f'Seu nome completo é {nome}')
print(f'Seu primeiro nome é {n[0]}')
print(f'Seu ultimo nome é {n[-1]}')