msg = input('Digite algo:')
print('O tipo primitivo desse valor é :',type(msg))
print('Só tem espaços ?',msg.isspace())
print('Só tem letras ?',msg.isalpha())
print('Só tem números ?',msg.isnumeric())
print('Tem letras e números ?',msg.isalnum())
print('Está com todas as letras em maiúsculo ?',msg.isupper())
print('Está com todas as letras em minúsculo ? ',msg.islower())
print('Está com a primeira letra me maiúsculo ?',msg.istitle())
